# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 261581940123f6ad236d22483b561a1733a7c4515909b39975a059ff88f6c314f0ef16b324186eff1a41efd8409612fa8ae05003aecd7013cb6f4cbaa20a1ba6

test:
  secret_key_base: c4011605cae3c25ff699a7b90b92a82800b98484a8aff39da5c05667ece595fe63bb9c7277b7d9fc885e399a527d3c249654027a3f8463c40e20c96bcbb27484

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
